model:
  model_path: models/model.pkl
  encoder_path: models/encoder.pkl

acquire:
  
  get_file:
    recent_transactions:
      url: https://filebin.net/tniv4fxc1k45dyrv/recent_transactions.csv
      file_name: data/external/recent_transactions.csv
    stockwatcher:
      url: https://filebin.net/tniv4fxc1k45dyrv/house_stock_watcher_api_data.csv
      file_name: data/external/stockwatcher.csv
    current_price: 
      url: https://filebin.net/tniv4fxc1k45dyrv/yahoo_api_current_price.csv
      file_name: data/external/current_price.csv 
    transact_price:
      url: https://filebin.net/tniv4fxc1k45dyrv/yahoo_api_transaction_price.csv
      file_name: data/external/transact_price.csv   
  
  upload_s3:
    recent_transactions: data/external/recent_transactions.csv
    stockwatcher: data/external/stockwatcher.csv
    current_price: data/external/current_price.csv 
    transact_price: data/external/transact_price.csv 

create_db:
  local_path: data/external/recent_transactions.csv

clean:
  stockwatcher:
    local_path: data/s3_downloads/stockwatcher.csv
  transact:
    local_path: data/s3_downloads/transact_price.csv
  current:
    local_path: data/s3_downloads/current_price.csv
  filter:
    columns: ['transaction_date',
              'disclosure_date',
              'disclosure_year',
              'cap_gains_over_200_usd',
              'asset_description',
              'ptr_link',
              'date_x',
              'date_y',
              'district',
              'current_price']
  s_cleanup:
    save_path: data/clean/clean.csv

  download_s3:
      rt:
        sep: ','
        local_path: data/s3_downloads/recent_transactions.csv
      sw:
        sep: ','
        local_path: data/s3_downloads/stockwatcher.csv
      cp: 
        sep: ','
        local_path: data/s3_downloads/current_price.csv 
      tp:
        sep: ','
        local_path: data/s3_downloads/transact_price.csv 

train:
  local_path: data/clean/clean.csv
  train:
    categ: ['owner',
            'ticker',
            'type',
            'amount',
            'representative']
    response: 'response'
    results_path: models/model_results.yaml
    model_path: models/model.pkl
    encoder_path: models/encoder.pkl
    test_size: 0.10
    random_state: 29
    max_iter: 5000

